title:
  "Hreflang"
description:
  "International SEO Strategy for Global Website Expansion based on Languages and Locations"
github:
  "ProcLib"

permalink:
  pretty

theme:
  jekyll-theme-cayman

gems:
  - jekyll-sitemap
  - jekyll-feed
