title:
  "Hreflang"
description:
  "International SEO strategy for different website Global Expansions through multiple Languages and/or Locations"
github:
  "ProcLib"

permalink:
  pretty

theme:
  jekyll-theme-cayman

gems:
  - jekyll-sitemap
  - jekyll-feed
